version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/server
    overwrite: true
hooks:
  ApplicationStop:
    - location: /hooks_scripts/application-stop.sh
      timeout: 300
  BeforeInstall:
    - location: /hooks_scripts/before_install.sh
      timeout: 300
  ApplicationStart:
    - location: /hooks_scripts/application-start.sh
      timeout: 300
