version: 0.0
os: linux
files:
  - source: '/React.js + Node.js/backend'
    destination: /home/ubuntu/server
    overwrite: true
hooks:
  ApplicationStop:
    - location: /hooks_scripts/application-stop.sh
      timeout: 300
  ApplicationStart:
    - location: /hooks_scripts/application-start.sh
      timeout: 300
